// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXdHpDWX83cxbtAZwxleYw7M7D6lUqi4Q',
    appId: '1:488467682292:web:cfbc5f0e1019393f0b5fa1',
    messagingSenderId: '488467682292',
    projectId: 'facebook-4df85',
    authDomain: 'facebook-4df85.firebaseapp.com',
    storageBucket: 'facebook-4df85.firebasestorage.app',
    measurementId: 'G-QTM70S390Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7XEPm6QQJ8lpt_r66H9xuE42qEKK49Vc',
    appId: '1:488467682292:android:0592d1519ed880d00b5fa1',
    messagingSenderId: '488467682292',
    projectId: 'facebook-4df85',
    storageBucket: 'facebook-4df85.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDBlx9iGWOM3Yi32iRtcVAjaskgcZOvqQ',
    appId: '1:488467682292:ios:061d77b2f9a54b2a0b5fa1',
    messagingSenderId: '488467682292',
    projectId: 'facebook-4df85',
    storageBucket: 'facebook-4df85.firebasestorage.app',
    iosBundleId: 'com.example.facebook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDBlx9iGWOM3Yi32iRtcVAjaskgcZOvqQ',
    appId: '1:488467682292:ios:061d77b2f9a54b2a0b5fa1',
    messagingSenderId: '488467682292',
    projectId: 'facebook-4df85',
    storageBucket: 'facebook-4df85.firebasestorage.app',
    iosBundleId: 'com.example.facebook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXdHpDWX83cxbtAZwxleYw7M7D6lUqi4Q',
    appId: '1:488467682292:web:611eb662f503942d0b5fa1',
    messagingSenderId: '488467682292',
    projectId: 'facebook-4df85',
    authDomain: 'facebook-4df85.firebaseapp.com',
    storageBucket: 'facebook-4df85.firebasestorage.app',
    measurementId: 'G-0RRWR9Y7R9',
  );
}
